dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: vc7KbFJFcC62Yb0F6Kaohu3DpvY4DBqGLDSNa5LFRu9W1SA5uQqrYIyNlkHXeKn/0ay1jME7PJYnRAxe77W36HDyh8JhFOTJGx90np+CJHd+W7lAN4fyLYxvqbCxcTew7o+KlS3dLitCChC+8sQ0H8HDkEw+6PacZBOfMkrst9iIGA2IzSpPfYP4i5oGFHRKUMkld3bkGfxc4rcMf0B7QkViKCdAxOc29/oPprocerp4z6Qi25CV1G1dNL8ZfE2YDhr5NJsNn/9Ui79LQ8FGBJoEOrJcTlCijz6JjRNHZbu4J++wyD3wJtfrpfI6IXX7xgnAyDBty1BKcLUpF74wjGu5DbRE9hLxHFklfeEVews2K36uRX2qmBaLtb4jakN2JcwDEP7wA+rII/VD1ld4u+yemoU4IQ9OPKtJM/hQX+bIvWBCr9vzs49e8s0s8cmEZC8XtfxkRgnslYhqk6Z8VkEm6CPK6WlMfLfuZYBN0Hg/zHr16uR8HCVj3nDKmKLEtG2txBAQZAi0hysgPC5ICvAeJo5uzGHlbT1QqBJBziqjGM8OMbie+8dR6viGXj/QxUynhAN3GXang87J15lcX8BfytkyklJO7yfp2GTIJZ73de7K747GTJvMK2A5Zh0/rtCpeXUDv8EKjH8FWeFxQlnVifUc2pzHXjW8S28EuM0=
  - secure: UwM6A7fBiJovj6LeHg4CbM4IcsDcMN/Uc79JEalO12/pVMLaVOx8Jbo9trxDCSFHrF2ojpSnlZjFCPOO4YaCk7qQ1f58/FX5ZgkxNeq3uQ7fFpgBDJGmUdJFsQb2yS/1JCL/bV8YIlUhNAjIyempEuqrgRPwyo822BQ2gwA6gkD5n7ATIixi/vRQM1a4Fq2W9V2R1Ub+QmCoYyFo93f1A2yJaf4iCAcRaajxSkW0e4iNRRK/Ztm6iynF88onDRFp7iMHcZIbIhrEkIHxGd6cX/ayQoyKOf+5+PpKpXbf1CuAK7aQCzUqgdZgYRGGqY4FyyqG9ahV8EBkheA1dq0m9/EY3+ymCzQrWdEPljPbR7yNZSoBJunKPTVw+vw/aITlY+RygBmwnMA1/j29b6K/hrVjHrTpZORSmKlWj9o8JCnpkvLkgr8l6YulEN1qoA0CXy8eRuel39l71Kg4r+RXkWEVIvbExKTtFC6H+Uyi4W/484cq4fXK7oGqy0AQm3qAa9HYCQHyUfJUDh1fXy6gca0PRSayi9lAfadrWtmfo2a5z7NaHK0sHeCqmwB4Qgc5SjxDD2CFMius3YTUCxEBdCkzmKx8PSeVQ/12SwkOkuptDC/1ChaG1CQuHh4uF6QM7/LUVdp0Hg4cKOJM3KAJJ7dabKkDqbYoNqZ1MmFUmdQ=
  - secure: oM8n4jkS+0bQjFYCp5T9z2OzyzLO8NE11akPcDj5lKwU4Cq3zFwRrrN0glwmewnONfrU9K2DiYzoX+gPAi6D6v4BQEFrDxXDKYCHyaxL/Yqv+SsHvAWsEyxQWpXHAFrqTVohyz1Ycw7Ct+xEDBYbMSW/xg0LfbUbU2kR9AnWYMBXfNmK4liQEk6tva+pce8CCKPf8EYqwj6RdfMLy1uQtAgodIlbvXfPuhkH527QpcKh+zzdwBYPjTeD/Q7f6KBi/0eZiWVTDMDQAUZJJlEuGznoxXMuM/BQ24n/amVBmI1iX0vFszwly0cCR2cb0YAcq7yA00RzgglJYbehjNTKekr/vzJ0wmBGsY6CAkaqHfAhpPeFPGAjNQK9jSK3wv6eJw5cxl7PiMHvKiwDn2lFJSdLbwTnNR08FqD7M7V+wyVd/NB4iBksRV3KDIgz1HDeLbdOemshh1HjnU39GIJSKcYQ0yYJE+y+6XMoCq1HE66pAhEC+K64pYgr0OxhQXfW36ka5s/zTtr5Pp6i8e1up2fnN24gMBZiOz+RXqQUxq3s0+KBUW5RUxRiAxGRYHoKYm+EQxlALI5GM1VKSbUIcQmyNUxSxoYbUlxMYvDwZ25EIjH3HVTxwq8rfVIYTnGbdhOJ9Y4tLcw9jU2CjbA4/TO5QfIBp2d/vtv7dRfTI9k=
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
